proxy_headers_hash_max_size 1024;
proxy_headers_hash_bucket_size 128;

limit_req_zone $binary_remote_addr zone=steamkb_public:10m rate=10r/s;
limit_req_zone $binary_remote_addr zone=steamkb_search:10m rate=3r/s;
limit_req_zone $binary_remote_addr zone=steamkb_admin:10m rate=1r/s;
limit_conn_zone $binary_remote_addr zone=steamkb_connections:10m;
